# In this example, vcpkg has been added as a submodule (`git submodule add https://github.com/Microsoft/vcpkg`).
name: "vcpkg binary Package"

on:
  # push:
  #   branches:
  #     - main
  #   tags:
  #     - v1.**
  # pull_request:
  # Enable a workflow to be triggered manually
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish-gpr:
    # In this example, Vcpkg has been added as a submodule (`git submodule add https://github.com/Microsoft/vcpkg`).
    name: Publish to GitHub Package Registry(GPR) with ${{ matrix.os }}-${{ matrix.triplet.mono }} vcpkg binary packages 
    strategy:
      matrix:
        include:
          - os: "windows-2019"
            triplet: "x64-windows"
            mono: ""
          - os: "ubuntu-20.04"
            triplet: "x64-linux"
            # To run `nuget.exe` on non-Windows platforms, we must use `mono`.
            mono: "mono"
    runs-on: ${{ matrix.os }}
    permissions:
      # Needs to publish to GitHub Packages
      packages: write
      contents: read
    env:
      VCPKG_BINARY_SOURCES: "clear;nuget,GitHub,readwrite"
      # Replace <OWNER> with your organization name
      OWNER: "liviaerxin"
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: bootstrap vcpkg in Windows
        if: runner.os == 'Windows'
        run: |
          echo "The operating system on the runner is $env:OWNER, $env:VCPKG_BINARY_SOURCES."
          ./vcpkg/bootstrap-vcpkg.bat
      
      - name: bootstrap vcpkg in non Windows
        if: runner.os != 'Windows'
        run: |
          pwd
          ls -al ./vcpkg
          echo "The operating system on the runner is not Windows, it's $RUNNER_OS. $VCPKG_BINARY_SOURCES."
          ./vcpkg/bootstrap-vcpkg.sh
      
      # This step assumes `vcpkg` has been bootstrapped (run `./vcpkg/bootstrap-OWNER`)
      - name: "Setup NuGet Credentials"
        shell: "bash"
        run: |
          set -x
          nuget="$(./vcpkg/vcpkg fetch nuget | tail -n 1)"

          ${{ matrix.mono }} "${nuget}" \
            sources add \
            -source "https://nuget.pkg.github.com/${OWNER}/index.json" \
            -storepasswordincleartext \
            -name "GitHub" \
            -username "${OWNER}" \
            -password "${{ secrets.GITHUB_TOKEN }}"
          ${{ matrix.mono }}  "${nuget}" \
            setapikey "${{ secrets.GITHUB_TOKEN }}" \
            -source "https://nuget.pkg.github.com/${OWNER}/index.json"

      # Omit this step if you're using manifests
      - name: "vcpkg package restore"
        shell: "bash"
        run: >
          ./vcpkg/vcpkg install sqlite3 cpprestsdk --triplet ${{ matrix.triplet }}
